-- MySQL Script generated by MySQL Workbench
-- Thu Nov 24 22:43:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema estrena_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `estrena_db` ;

-- -----------------------------------------------------
-- Schema estrena_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estrena_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `estrena_db` ;

-- -----------------------------------------------------
-- Table `estrena_db`.`user_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estrena_db`.`user_perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `nameCategory` VARCHAR(40) NOT NULL,
  `fechaDeBaja` DATE NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idcategories_UNIQUE` ON `estrena_db`.`user_perfil` (`idPerfil` ASC);


-- -----------------------------------------------------
-- Table `estrena_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estrena_db`.`users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `idPerfil` INT NOT NULL,
  `firstName` VARCHAR(50) NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `tel` VARCHAR(15) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fechaDeBaja` DATE NULL,
  PRIMARY KEY (`idUser`),
  CONSTRAINT `idPerfil`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `estrena_db`.`user_perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idusers_UNIQUE` ON `estrena_db`.`users` (`idUser` ASC);

CREATE INDEX `idCategory_idx` ON `estrena_db`.`users` (`idPerfil` ASC);


-- -----------------------------------------------------
-- Table `estrena_db`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estrena_db`.`product_category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `nameCategory` VARCHAR(40) NOT NULL,
  `fechaDeBaja` DATE NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idcategories_UNIQUE` ON `estrena_db`.`product_category` (`idCategory` ASC);


-- -----------------------------------------------------
-- Table `estrena_db`.`product_size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estrena_db`.`product_size` (
  `idSize` INT NOT NULL AUTO_INCREMENT,
  `nameSize` VARCHAR(40) NOT NULL,
  `fechaDeBaja` DATE NULL,
  PRIMARY KEY (`idSize`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idcategories_UNIQUE` ON `estrena_db`.`product_size` (`idSize` ASC);


-- -----------------------------------------------------
-- Table `estrena_db`.`product_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estrena_db`.`product_color` (
  `idColor` INT NOT NULL AUTO_INCREMENT,
  `nameColor` VARCHAR(40) NOT NULL,
  `fechaDeBaja` DATE NULL,
  PRIMARY KEY (`idColor`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idcategories_UNIQUE` ON `estrena_db`.`product_color` (`idColor` ASC);


-- -----------------------------------------------------
-- Table `estrena_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estrena_db`.`products` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `image` VARCHAR(30) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `idColor` INT NOT NULL,
  `idSize` INT NOT NULL,
  `idCategory` INT NOT NULL,
  PRIMARY KEY (`idProduct`),
  CONSTRAINT `idCategory`
    FOREIGN KEY (`idCategory`)
    REFERENCES `estrena_db`.`product_category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idColor`
    FOREIGN KEY (`idColor`)
    REFERENCES `estrena_db`.`product_color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSize`
    FOREIGN KEY (`idSize`)
    REFERENCES `estrena_db`.`product_size` (`idSize`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idusers_UNIQUE` ON `estrena_db`.`products` (`idProduct` ASC);

CREATE INDEX `idCategory_idx` ON `estrena_db`.`products` (`idCategory` ASC);

CREATE INDEX `idColor_idx` ON `estrena_db`.`products` (`idColor` ASC);

CREATE INDEX `idSize_idx` ON `estrena_db`.`products` (`idSize` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
